### ISSUE TITLE
Unable to recover due to lack of public randomness

### ISSUE THREAD

**Issue by gitferry** [babylonlabs-io/finality-provider#115]
After a long downtime of an fp, the committed public randomness could be run out. During bootstrapping, it should ensure the committed randomness is sufficient. This could lead to the following errors:

```
Whoops. There was an error while executing your fpd CLI 'failed to start app: failed to start finality-provider 5238b0223ea9d9d59ed4371e6248bfc55b14193f862c4773ac2972d70289541b instance: failed to bootstrap the finality-provider 5238b0223ea9d9d59ed4371e6248bfc55b14193f862c4773ac2972d70289541b: failed to send a batch of finality signatures to the consumer chain: rpc error: code = Unknown desc = rpc error: code = Unknown desc = failed to execute message; message index: 6: Public randomness not found for finality provider 5238b0223ea9d9d59ed4371e6248bfc55b14193f862c4773ac2972d70289541b at height 88301: execute wasm contract failed [CosmWasm/wasmd@v0.51.0/x/wasm/keeper/keeper.go:422] with gas used: '1728195': unknown request'%
```

```
Whoops. There was an error while executing your fpd CLI 'failed to start app: failed to start finality-provider dbaec7f5ccaf56a3b02d0af1ae1480623f6c1d132450c90e0da391ee88a3aa98 instance: failed to bootstrap the finality-provider dbaec7f5ccaf56a3b02d0af1ae1480623f6c1d132450c90e0da391ee88a3aa98: failed to get public randomness inclusion proof list: public randomness proof not found
```

**Comment by bap2pecs** [comment]
any updates on this?

jfyi I am currently adding another daemon command `fpd command-pubrand <fpBtcPk> <targetHeight>` to help recover FP stuck in this case

cc @SebastianElvis @gitferry

**Comment by bap2pecs** [comment]
What will the proper fix look like? I think we will need to get rid of fast sync in bootstrap() but the change is non-trivial

**Comment by bap2pecs** [comment]
> jfyi I am currently adding another daemon command `fpd commit-pubrand <fpBtcPk> <targetHeight>` to help recover FP stuck in this case

https://github.com/babylonlabs-io/finality-provider/pull/131

**Comment by gitferry** [comment]
Thanks for the reminder. The goal is to make sure sending votes and committing randomness are entirely independent routines (fp will not have voting power if no timestamped randomness). Will look into the solution this week

**Comment by bap2pecs** [comment]
> @bap2pecs I was wondering which version of Babylon are you running? Is btc-timestamping included? cc @SebastianElvis. If not, then it makes sense as after btc-timestamping inclusion, we have decided to make `btc-timestamping` part of voting power assignment. That is, if there no btc-timestamped pub rand on Babylon, the fp will be assgined with `0` voting power

Euphrates-0.5.0

**Comment by gitferry** [comment]
> Euphrates-0.5.0

I looked the code I found that the BTC-timestamping is included. Then that's weried. It seems the fp has decided to vote (vp > 0) but failed.

For the first error `Public randomness not found for finality provider` it seems error from the smart contract side and I don't know why.

For the second error `public randomness proof not found` is returned when `vp > 0` meaning the pub rand commit has been made to Babylon and got BTC-timestamped. Could it be that the db is corrupted? To me it seems the only reason because the proof is stored to db before sending the pub rand commit https://github.com/babylonlabs-io/finality-provider/blob/cb1c05ee7e349844916aeef521b3f61234b998b4/finality-provider/service/fp_instance.go#L642

**Comment by bap2pecs** [comment]
> I looked the code I found that the BTC-timestamping is included. Then that's weried. It seems the fp has decided to vote (vp > 0) but failed.

root cause is the OP consumer `QueryFinalityProviderHasPower` didn't check PR. So we need to update https://github.com/babylonlabs-io/finality-provider/blob/base/consumer-chain-support/clientcontroller/opstackl2/consumer.go#L270 to honor the new rule (i.e. no power if PR is not timestamped)

**Comment by gitferry** [comment]
> same for the second error. it's related as well.

Makes sense. Do you think we can close this issue and you raise another one more related?

**Comment by bap2pecs** [comment]
> Makes sense. Do you think we can close this issue and you raise another one more related?

sure
