### ISSUE TITLE
`fpd keys add` unexpectedly overwrite fpd.conf key field

### ISSUE THREAD

**Issue by bap2pecs** [babylonlabs-io/finality-provider#136]
found this while doing some testing. after debugging, I found it's due to this command will modify my fpd.conf file so I got key not found error

I'd vote to remove this post-run hook:

```
	keyAddCmd.PostRunE = helper.RunEWithClientCtx(func(ctx client.Context, cmd *cobra.Command, args []string) error {
		// check the config file exists
		cfg, err := fpcfg.LoadConfig(ctx.HomeDir)
		if err != nil {
			return nil // config does not exist, so does not update it
		}

		keyringBackend, err := cmd.Flags().GetString(sdkflags.FlagKeyringBackend)
		if err != nil {
			return err
		}

		// write the updated config into the config file
		cfg.BabylonConfig.Key = args[0]
		cfg.BabylonConfig.KeyringBackend = keyringBackend
		fileParser := goflags.NewParser(cfg, goflags.Default)

		return goflags.NewIniParser(fileParser).WriteFile(fpcfg.ConfigFile(ctx.HomeDir), goflags.IniIncludeComments|goflags.IniIncludeDefaults)
	})
```

@gitferry @SebastianElvis wdyt?

**Comment by bap2pecs** [comment]
> This is intentional so that after `keys add` all the interactions with Babylon will be using this key. Why did you get `key not found` error?

ok it seems `keys add` will set the `Key` field to empty string in the `[opstackl2]` section. this needs to be fixed

but I do feel this side-effect of modifying the config file is unexpected. we should at least add a comment or add a flag

**Comment by gitferry** [comment]
Make sense. I think we probably can remove this part so that after `fpd keys add`, we should instruct the user to change the config file. @RafilxTenfen @samricotta what do you guys think?

**Comment by RafilxTenfen** [comment]
> Make sense. I think we probably can remove this part so that after `fpd keys add`, we should instruct the user to change the config file. @RafilxTenfen @samricotta what do you guys think?

Agree, we could remove this update in config and alert that the config needs to point to the new key
cc @babylon-devops this might affect some scripts

**Comment by RafilxTenfen** [comment]
will be done at https://github.com/babylonlabs-io/finality-provider/issues/143

**Comment by RafilxTenfen** [comment]
ops, wait I read it wrong, the #143 will do for eotsd
another PR can be made to remove this behavior in fpd
