### ISSUE TITLE
chore: enable govet linter

### ISSUE THREAD

**Issue by bap2pecs** [babylonlabs-io/finality-provider#38]
context: https://github.com/babylonlabs-io/finality-provider/issues/29

before enabling it, there are lots of places to fix

**Comment by Lazar955** [comment]
hi @bap2pecs, I think this one can be closed, [ref](https://github.com/babylonlabs-io/finality-provider/blob/08ec9ab44d572bf68e9542a4b1075d7a03ffbbbf/.golangci.yml#L30)
